name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/ost_key.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app Release AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/ost_key.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew :app:bundleRelease

      - name: Build wear Release AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/ost_key.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew :wear:bundleRelease

      - name: Upload app AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/*.aab

      - name: Upload wear AAB
        uses: actions/upload-artifact@v4
        with:
          name: wear-release
          path: wear/build/outputs/bundle/release/*.aab